/* Full time first time degree seeking student subquery receiving aid--group 2a */
/* IPEDS flag */

select a.year, a.unit, a.division, count(distinct a.student_ssn), sum(uwsa.stfa_aid_a.fin_aid_amount),
    decode(uwsa.stfa_aid_a.fin_aid_type,
		    '10','B:STATE/LOCAL GRANT',
		'11','B:STATE/LOCAL GRANT',
		'12','B:STATE/LOCAL GRANT',
		'16','B:STATE/LOCAL GRANT',
		'17','B:STATE/LOCAL GRANT',
		'18','B:STATE/LOCAL GRANT',
		'19','B:STATE/LOCAL GRANT',
		'20','E:OTHER GRANT',
		'21','B:STATE/LOCAL GRANT',
		'22','C:INST GRANT',
		'24','A:PELL GRANT',
		'25','C:INST GRANT',
		'28','A:FED GRANT',
		'29','B:STATE/LOCAL GRANT',
		'31','A:FED GRANT',
		'33','A:FED GRANT',
		'34','A:FED GRANT',
		'35','A:FED GRANT',
		'36','A:FED GRANT',
		'37','A:FED GRANT',
		'38','B:STATE/LOCAL GRANT',
		'39','B:STATE/LOCAL GRANT',
		'41','A:FED GRANT',
		'42','A:FED GRANT',	
		'43','A:FED GRANT',	
		'44','A:FED GRANT',
		'45','A:FED GRANT',
		'46','E:OTHER GRANT',
		'47','B:STATE/LOCAL GRANT',
		'48','B:STATE/LOCAL GRANT',
		'49','F:PLUS',
		'52','D1:OTHER LOAN',
		'53','D1:OTHER LOAN',
		'54','D:FEDERAL LOAN',
		'56','D:FEDERAL LOAN',
		'57','D:FEDERAL LOAN',
		'58','D:FEDERAL LOAN',
		'59','D1:OTHER LOAN',
		'60','D:FEDERAL LOAN',
		'61','D:FEDERAL LOAN',
		'62','D:FEDERAL LOAN',
		'63','D1:OTHER LOAN',
		'65','D1:OTHER LOAN',
		'66','D1:OTHER LOAN',
		'67','F:PLUS',
		'68','D:FEDERAL LOAN',
		'69','D:FEDERAL LOAN',
		'74','B:STATE/LOCAL GRANT',
		'75','E:OTHER GRANT',
		'76','D2:WS',
		'78','D2:WS',
		'79','B:STATE/LOCAL GRANT',
		'80','D2:WS',
		'83','E:OTHER GRANT',
		'84','E:OTHER GRANT',
		'85','B:STATE/LOCAL GRANT',
		'85','B:STATE/LOCAL GRANT', 
		'91','D:FEDERAL LOAN',
		'92','D:FEDERAL LOAN',
		'93','F:PLUS',
		'OTHER')
		
from

(select year, unit,division, student_ssn
			from UWSA.STUDENT_ANALYTICAL
			where year = '201314' and
			term = '1' and
			Classif in ('A','B','C','D') AND 
			ipeds_flag = 'Y' and
			ipeds_part_time = 'N' and
			entr_status = 'N' 
		
			group by year, unit,division,student_ssn) a,

		UWSA.STFA_AID_A
		
		where
	 (UWSA.STFA_AID_A.FIN_AID_TYPE not in ('13','14','15','67','70','71','72','76','94','95','96','97','99')) and 
		UWSA.STFA_AID_A.year = '201314' and 
		 UWSA.STFA_AID_A.student_ssn = a.student_ssn and 
		  UWSA.STFA_AID_A.unit  = a.unit  and 
	  UWSA.STFA_AID_A.Division = a.division

group by a.year, a.unit, a.division,
  decode(uwsa.stfa_aid_a.fin_aid_type,
		    '10','B:STATE/LOCAL GRANT',
		'11','B:STATE/LOCAL GRANT',
		'12','B:STATE/LOCAL GRANT',
		'16','B:STATE/LOCAL GRANT',
		'17','B:STATE/LOCAL GRANT',
		'18','B:STATE/LOCAL GRANT',
		'19','B:STATE/LOCAL GRANT',
		'20','E:OTHER GRANT',
		'21','B:STATE/LOCAL GRANT',
		'22','C:INST GRANT',
		'24','A:PELL GRANT',
		'25','C:INST GRANT',
		'28','A:FED GRANT',
		'29','B:STATE/LOCAL GRANT',
		'31','A:FED GRANT',
		'33','A:FED GRANT',
		'34','A:FED GRANT',
		'35','A:FED GRANT',
		'36','A:FED GRANT',
		'37','A:FED GRANT',
		'38','B:STATE/LOCAL GRANT',
		'39','B:STATE/LOCAL GRANT',
		'41','A:FED GRANT',
		'42','A:FED GRANT',	
		'43','A:FED GRANT',	
		'44','A:FED GRANT',
		'45','A:FED GRANT',
		'46','E:OTHER GRANT',
		'47','B:STATE/LOCAL GRANT',
		'48','B:STATE/LOCAL GRANT',
		'49','F:PLUS',
		'52','D1:OTHER LOAN',
		'53','D1:OTHER LOAN',
		'54','D:FEDERAL LOAN',
		'56','D:FEDERAL LOAN',
		'57','D:FEDERAL LOAN',
		'58','D:FEDERAL LOAN',
		'59','D1:OTHER LOAN',
		'60','D:FEDERAL LOAN',
		'61','D:FEDERAL LOAN',
		'62','D:FEDERAL LOAN',
		'63','D1:OTHER LOAN',
		'65','D1:OTHER LOAN',
		'66','D1:OTHER LOAN',
		'67','F:PLUS',
		'68','D:FEDERAL LOAN',
		'69','D:FEDERAL LOAN',
		'74','B:STATE/LOCAL GRANT',
		'75','E:OTHER GRANT',
		'76','D2:WS',
		'78','D2:WS',
		'79','B:STATE/LOCAL GRANT',
		'80','D2:WS',
		'83','E:OTHER GRANT',
		'84','E:OTHER GRANT',
		'85','B:STATE/LOCAL GRANT',
		'85','B:STATE/LOCAL GRANT', 
		'91','D:FEDERAL LOAN',
		'92','D:FEDERAL LOAN',
		'93','F:PLUS',
		'OTHER');
`
			